### ISSUE TITLE
Ags dots

### ISSUE THREAD

**Issue by havvvsen** [celesrenata/nix-flakes#1]
Finally someone who made end4 dots work on nixos. You are really awesome. How do I get only ags from your dots and are the patches a must for it to work.Am new to nixos

**Comment by celesrenata** [comment]
take AGS from my flakes, and then pass it into your home.nix as an import. You will then be able to do pretty much whatever you want. My flakes pull .config from my repo and place into .configstaging, you can easily modify it to pull end-4's .config folder and then it will copy it to .config for you, leaving them available for editing.
